name: fenicsx-env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=4
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - alsa-lib=1.2.14
  - attr=2.5.1
  - attrs=25.3.0
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - blis=0.9.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.17.1
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.16.0
  - charset-normalizer=3.4.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.16.2
  - double-conversion=3.3.1
  - fenics-basix=0.9.0
  - fenics-basix-nanobind-abi=0.2.1.13
  - fenics-dolfinx=0.9.0
  - fenics-ffcx=0.9.0
  - fenics-libbasix=0.9.0
  - fenics-libdolfinx=0.9.0
  - fenics-ufcx=0.9.0
  - fenics-ufl=2024.2.0
  - fftw=3.3.10
  - fmt=11.1.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - freetype=2.13.3
  - frozenlist=1.6.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gl2ps=1.4.2
  - graphite2=1.3.13
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - hypre=2.32.0
  - icu=75.1
  - idna=3.10
  - jsoncpp=1.9.6
  - kahip=3.19
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libadios2=2.10.2
  - libaec=1.1.3
  - libamd=3.3.3
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-devel=1.86.0
  - libboost-headers=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcap=2.75
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang-cpp20.1=20.1.5
  - libclang13=20.1.5
  - libcolamd=3.3.4
  - libcups=2.3.3
  - libcurl=8.13.0
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.0
  - libfabric=2.1.0
  - libfabric1=2.1.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libklu=2.3.5
  - liblapack=3.9.0
  - libllvm20=20.1.5
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libptscotch=7.0.6
  - libsanitizer=13.3.0
  - libscotch=7.0.6
  - libsodium=1.0.20
  - libspqr=4.3.4
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsuitesparseconfig=7.10.1
  - libsystemd0=257.4
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libudev1=257.4
  - libumfpack=6.3.5
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - loguru=0.7.3
  - lz4-c=1.10.0
  - matplotlib-base=3.10.3
  - metis=5.1.0
  - mpi=1.0.1
  - mpi4py=4.0.3
  - mpich=4.3.0
  - msgpack-python=1.1.0
  - multidict=6.4.4
  - mumps-include=5.7.3
  - mumps-mpi=5.7.3
  - munkres=1.1.4
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - packaging=25.0
  - parmetis=4.0.3
  - pcre2=10.45
  - petsc=3.23.2
  - petsc4py=3.23.2
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.0
  - pkg-config=0.29.2
  - platformdirs=4.3.8
  - pooch=1.8.2
  - proj=9.6.0
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pugixml=1.15
  - pycparser=2.22
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyvista=0.45.2
  - qhull=2020.2
  - qt6-main=6.9.0
  - rdma-core=57.0
  - readline=8.2
  - requests=2.32.3
  - scalapack=2.2.0
  - scooby=0.10.1
  - setuptools=80.8.0
  - six=1.17.0
  - slepc=3.23.1
  - slepc4py=3.23.1
  - snappy=1.2.1
  - spdlog=1.15.3
  - sqlite=3.49.2
  - superlu=7.0.1
  - superlu_dist=9.1.0
  - sysroot_linux-64=2.17
  - tbb=2022.1.0
  - tk=8.6.13
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - ucx=1.18.1
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - utfcpp=4.0.6
  - vtk-base=9.4.2
  - wayland=1.23.1
  - wheel=0.45.1
  - wslink=2.3.4
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.0
  - zeromq=4.3.5
  - zfp=1.0.1
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
